FROM openjdk:8-jre-stretch

RUN apt-get update && apt-get install -y vim git openjdk-8-jdk

WORKDIR /opt

RUN cd /opt && git clone git://github.com/Netflix/SimianArmy.git . && ./gradlew build

CMD bash
